### ISSUE TITLE
dbcparser parses factor incorrectly

### ISSUE THREAD

**Issue by ozzdemir** [GENIVI/CANdb#21]
I use  "ford_cgea1_2_bodycan_2011.dbc" for testing CDS, it succesfuly parses (actually it is the reason I am using it, from [this issue](https://github.com/GENIVI/CANdevStudio/issues/196#issue-552140596)). I was trying to send signal using CanSignalSender, but cansignalencoder gave the following error.

`[cds] [error] [signalToRaw():cansignalencoder_p.cpp@104] Factor for HvacEvap_Te_Offst signal is 0! Singal encoding failed.`

I tracked error a little bit and found out that factor of can message is parsed incorrectly as 0. Then checked other messages and found that all factors are parsed as integers (by observing CanSignalData block) and they are floor'ed. Table can be seen in the figure below.

![image](https://user-images.githubusercontent.com/30624975/75337624-67eec600-589e-11ea-9792-bf6c731dfc7b.png)
The message I am playing is the one with id 0x326 and it is given below.
> BO_ 806 Compressor_Req: 8 XXX
>  SG_ HvacEvap_Te_Rq : 33|10@0+ (0.125,-50.0) [0|0] "Degrees C" XXX
>  SG_ HvacEvap_Te_Actl : 17|10@0+ (0.125,-50.0) [0|0] "Degrees C" XXX
>  SG_ HvacAirCond_B_Rq : 7|1@0+ (1,0) [0|0] "" XXX
>  SG_ HvacEvap_Te_Offst : 1|10@0+ (0.125,-50.0) [0|0] "Degrees C" XXX

**Comment by rkollataj** [comment]
Which version of CANdevStudio are you using? There was a fix for floating point factors here: https://github.com/GENIVI/CANdb/commit/8dfed1a08a3f0747bbbc8d6418569a072768492e

This fix should be a part of version 1.0 already.

**Comment by ozzdemir** [comment]
I use version 1.0 release but I updated CANdb to recent version to solve [this issue](https://github.com/GENIVI/CANdevStudio/issues/196).

**Comment by rkollataj** [comment]
It works for me with CANdb 8dfed1a0 that is set by default.

![image](https://user-images.githubusercontent.com/19871188/75377993-2593ac00-58d3-11ea-864c-6ea09562b20a.png)

**Comment by ozzdemir** [comment]
After your response, I've been trying to build from source and I succeeded eventually. I tested with [8dfed1a](https://github.com/GENIVI/CANdb/commit/8dfed1a08a3f0747bbbc8d6418569a072768492e) but no change.  I also used the revisions that can be seen below which are latest ones, still no change. Factors are still false. I can't find any valid reason. 
![image](https://user-images.githubusercontent.com/30624975/75490651-9adfa980-59c5-11ea-9a7a-aa610dadebf6.png)
![image](https://user-images.githubusercontent.com/30624975/75492121-278b6700-59c8-11ea-86f3-33ef85f668e7.png)

Sorry, my response took some time since I had problems with Qt installations.

**Comment by ozzdemir** [comment]
I have found the culprit which was the std::stof as mentioned [here](https://www.reddit.com/r/cpp/comments/2e68nd/stdstod_is_locale_dependant_but_the_docs_does_not/?utm_source=share&utm_medium=web2x). std::stof was using "," decimal point separator due to my locale settings.

**Comment by ozzdemir** [comment]
Using `std::setlocale(LC_ALL, "C");` inside `DBCParser::parse()` before everything else solved problem, but it should be used in initialization I guess. Since I'm not that familiar with the project and its initialization procedure, I did not create a pull request.

**Comment by rkollataj** [comment]
I would never expect that locale settings can have impact on CANdb functionality... good work in figuring this out!

I will create fix for this. Thanks.

**Comment by rkollataj** [comment]
@ozzdemir Let me know if #22 fixes your problem.

**Comment by ozzdemir** [comment]
#22 does solve the problem.

**Comment by w0land** [comment]
#22 merged. I'm closing this ticket

**Comment by Check2016** [comment]
For me this issue still occurs. I'm using Ubuntu 18.04. and compiled CANdevStudio from source (https://github.com/GENIVI/CANdevStudio/commit/f5800970436ac9423a3bd3d2b3b669d6cd102e69) which should already have the fix (CANdb commit https://github.com/GENIVI/CANdb/commit/054c7ff4ee0b87770415abb41f69a9b019bd840e)

Switching my system locale from "German" to "United States" fixes the issue and the factors are parsed correctly.
