### ISSUE TITLE
"VAL_TABLE_" and "VAL_" DBC Signal parsing

### ISSUE THREAD

**Issue by enricop** [GENIVI/CANdb#32]
Hello,

in this file CANdb/src/dbcparser.cpp at line192:
```
    pegParser["val_entry"] = [&can_db, &phrasesPairs](const peg::SemanticValues&) {
        std::vector<CANdb_t::ValTable::ValTableEntry> tab;
        std::transform(phrasesPairs.begin(), phrasesPairs.end(), std::back_inserter(tab), [](const auto& p) {
            return CANdb_t::ValTable::ValTableEntry{ p.first, p.second };
        });
        can_db.val_tables.push_back(CANdb_t::ValTable{ "", tab });
        phrasesPairs.clear();
    };
```
the signal id/name is not parsed from the DBC file "VAL_TABLE_" and "VAL_" section, but just an empty string ("") is used. 

It should be placed in the "identifier" member of "ValTable" struct.

Would it be possible to fix this upstream or provide us just a suggestion on how to do it?
Thanks for your support,
enrico

**Comment by enricop** [comment]
any suggestion for implementing a perParser lamda for "VAL_" entries like the ones [here](https://github.com/commaai/opendbc/blob/master/tesla_can.dbc#L312)? @btaczala @rkollataj  @mguentner

**Comment by btaczala** [comment]
@enricop can you provide an example dbc file for this?

**Comment by enricop** [comment]
hello, I've sent you a mail with the dbc.

You can find also a "dbcparser.cpp" patch we are using to workaround this issue, but we are not expert on the parsing library/logic.
[candb.txt](https://github.com/GENIVI/CANdb/files/6284962/candb.txt)

Thank you very much for your support on this and your effort in removing boost as a dependency of CANdb.

**Comment by enricop** [comment]
this is the actual diff with the current upstream master branch code: 
[upstream_patch.txt](https://github.com/GENIVI/CANdb/files/6285006/upstream_patch.txt)

**Comment by enricop** [comment]
hello, we tested the "val_table" branch and it's ok

**Comment by btaczala** [comment]
@enricop Yeah I'll merge the val_table branch; the thing that's still missing is `VAL_` entries - I'm planning to add support for them

**Comment by enricop** [comment]
ok thank you. Linking the entries in the new `VAL_` data structure with the `VAL_TABLE_` data structure would be usefull too.
