### ISSUE TITLE
[embedded] Migration to PegLib C++17 for improving parsing performance?

### ISSUE THREAD

**Issue by enricop** [GENIVI/CANdb#39]
Hello,

we would like understand more about parsing performances of CANdb, and where cpu-time is actually spent when parsing a DBC.

In our application we are loading 2 DBC files:
- CAN1.dbc loaded in = 925[ms] -> which on ARM embedded system is almost 15[secs]
- CAN2.dbc loaded in = 1473[ms] -> which on ARM embedded system is almost 20[secs]

here is the perf flamegraph of the first 40seconds of the whole applications startup.

![parsing flamegraph](https://user-images.githubusercontent.com/667557/117782424-e7697a80-b241-11eb-8c0d-a91004a934cc.png)

We have many modules in the application, however DBC parsing, in particular peglib.h codepath, covers almost 50% of all startup cpu-time.

We tried to switch the [peglib submodule](https://github.com/yhirose/cpp-peglib) to the _master_ branch, and made some quick adjustments to compile with std::string_view support. However the CANdb parsing is entering an infinite loop...we are investigating further.

Do you think that, for improving the parsing performance on an iMX6 embedded system, this is the way to go?

thanks for your support

**Comment by enricop** [comment]
we were able to modify the dbcparser.cpp to support peglib c++17. These are the parsing duration for parsing the files on Desktop:

CAN1.dbc loaded in = 689[ms]
CAN2.dbc loaded in = 1177[ms]

they are reduced by 30%

**Comment by enricop** [comment]
hello, by reverting [this commit](https://github.com/GENIVI/CANdb/commit/ddf2e6414e9b085d427c994198fc30d199e654c1), which increases "cpp-peglib" submodule commit version, the performances from 20/30 seconds came back to 2/3 seconds on ARM iMX6 embedded systems.

going back to this [v1.3.7 cpp-peglib commit](https://github.com/yhirose/cpp-peglib/commit/11ed83e) the parsing time is the same on ARM systems as x86 systems.

**Comment by btaczala** [comment]
OK, I forgot that we're on cpp-peglib v0.1.14. I'll try to bump it to v1.3.7 then

**Comment by btaczala** [comment]
I'll also add some [benchmark](https://github.com/google/benchmark) tests and intergrate it with CI to track other performance degradations

**Comment by btaczala** [comment]
@enricop Does #40 fixes your performance problem?
