### ISSUE TITLE
Fix failing travis build

### ISSUE THREAD

**Issue by gunnarx** [GENIVI/CANdb#8]
Travis build fails, (as you have probably seen).

I looked into it since I wanted it fixed.  Summarizing (but you might know all this already):

- CMakeLists in CANdb build uses the module named GoogleTest, which is not found so the travis build fails.
- GoogleTest module was [introduced in cmake 3.9](https://cmake.org/cmake/help/v3.9/release/3.9.html)
- The Docker image that is used, **bartekt/can_dev_base_image**, has cmake version 3.8.2
- The current standard Travis image actually has 3.9.2 which should be enough.  I therefore tried the build without the docker image but then the latest gcc-6 was missing, so I stopped there.

In summary, either update cmake version in the container, or find another way to install gcc so that the travis-provided image can be used?
(By the way, it's not terribly efficient now to pull the 1GB+ build container for every build (it's not cached but pulled every time I believe?))

- I could not do the first option for you and send a PR because I don't know where the Dockerfile is at (not at https://github.com/bartekt from what I could see?, and also not in this (CANdb) repository)

If you can't update the base image or find an appropriate backport there's also this option by installing compiled cmake versions from cmake site, for example the shell installer can be convenient:
```
wget https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.sh
sudo bash cmake-3.11.2-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir
```

**Comment by w0land** [comment]
Issue has be fixed by @rkollataj with #9
